FROM node:lts-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

FROM node:lts-alpine
WORKDIR /app
COPY --from=builder /app/dist/to-do-list ./dist

EXPOSE 4000

CMD ["node", "dist/server/server.mjs"]